name: Code quality check
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Check the source code quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.16.9'

      - name: Install packages
        run: flutter pub get
      - name: Linter
        run: flutter analyze
      - name: build check
        run: flutter build apk
